export type Lang = 'en' | 'ta';

export const STRINGS = {
  en: {
    go: 'GO',
    caution: 'CAUTION',
    stop: 'STOP',
    do_not_cultivate: 'Do not cultivate today',
    coordinator_message: 'Coordinator message',
    today_conditions: "Today's conditions",
    forecast: '7-Day Forecast',
    updated: 'Updated',
    next_update: 'Next update',
    live: 'LIVE',
    simulated: 'SIMULATED',
    salinity: 'Salinity',
    temperature: 'Temperature',
    rainfall: 'Rainfall',
    wave_height: 'Wave Height',
    turbidity: 'Turbidity',
    simulator_warning: 'Simulator mode — data is not real',
    see_all: 'See all',
    back: 'Back',
    today_readings: "Today's Readings",
    coordinator_dashboard: 'Coordinator Dashboard',
    css_simulator: 'CSS Simulator',
    active_note: 'Active Note',
    clear_note: 'Clear note',
    post_note: 'Post a note to farmers',
    override_zone: 'Override zone',
    send_to_farmers: 'Send to farmers',
    open_simulator: 'Open Simulator',
    reset_to_live: 'Reset to live data',
    optimal: 'Optimal',
    simulator_mode: 'SIMULATOR MODE',
    simulator_not_real: 'Data shown is not real',
  },
  ta: {
    go: 'செல்',
    caution: 'எச்சரிக்கை',
    stop: 'நிறுத்து',
    do_not_cultivate: 'இன்று பயிரிட வேண்டாம்',
    coordinator_message: 'ஒருங்கிணைப்பாளர் செய்தி',
    today_conditions: 'இன்றைய நிலை',
    forecast: '7 நாள் முன்னறிவிப்பு',
    updated: 'புதுப்பிக்கப்பட்டது',
    next_update: 'அடுத்த புதுப்பிப்பு',
    live: 'நேரடி',
    simulated: 'உருவகப்படுத்தப்பட்டது',
    salinity: 'உப்புத்தன்மை',
    temperature: 'வெப்பநிலை',
    rainfall: 'மழைப்பொழிவு',
    wave_height: 'அலை உயரம்',
    turbidity: 'கலக்கம்',
    simulator_warning: 'சிமுலேட்டர் முறை — தரவு உண்மையானது அல்ல',
    see_all: 'அனைத்தும்',
    back: 'திரும்பு',
    today_readings: 'இன்றைய அளவீடுகள்',
    coordinator_dashboard: 'ஒருங்கிணைப்பாளர் டாஷ்போர்டு',
    css_simulator: 'CSS சிமுலேட்டர்',
    active_note: 'செயலில் உள்ள குறிப்பு',
    clear_note: 'குறிப்பை அழி',
    post_note: 'விவசாயிகளுக்கு குறிப்பு இடுக',
    override_zone: 'மண்டலத்தை மாற்று',
    send_to_farmers: 'விவசாயிகளுக்கு அனுப்பு',
    open_simulator: 'சிமுலேட்டரை திற',
    reset_to_live: 'நேரடி தரவுக்கு மீட்டமை',
    optimal: 'உகந்தது',
    simulator_mode: 'சிமுலேட்டர் முறை',
    simulator_not_real: 'காட்டப்படும் தரவு உண்மையானது அல்ல',
  },
} as const;

export type StringKey = keyof typeof STRINGS.en;
